apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-react-app
  name: my-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-react-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-react-app
    spec:
      containers:
      - image: cmreactdocker.azurecr.io/my-react-app:v1
        name: webapp
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 3000 
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: my-react-app
  labels:
    run: my-react-app
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: my-react-app
  type: LoadBalancer